import { describe, it, expect } from "vitest";
import { buildR2Key, buildCommentMarkdown } from "../src/worker/storage";

describe("buildR2Key", () => {
  it.each([
    ["/dashboard", "owner/repo/pr-1/dashboard.png", "simple route"],
    [
      "/settings/profile",
      "owner/repo/pr-1/settings-profile.png",
      "nested route",
    ],
    ["/", "owner/repo/pr-1/index.png", "root route"],
    ["/foo?bar=baz", "owner/repo/pr-1/foobarbaz.png", "special characters"],
  ])("slugifies %s -> %s (%s)", (route, expected) => {
    expect(buildR2Key("owner", "repo", 1, route)).toBe(expected);
  });
});

describe("buildCommentMarkdown", () => {
  it("builds markdown with screenshots", () => {
    const md = buildCommentMarkdown("abc1234567890", [
      {
        route: "/dashboard",
        description: "Main dashboard",
        url: "https://screenshots.tractorbeam.ai/o/r/pr-1/dashboard.png",
      },
      {
        route: "/settings",
        description: "Settings page",
        url: "https://screenshots.tractorbeam.ai/o/r/pr-1/settings.png",
      },
    ]);

    expect(md).toContain("## Visual Diff Screenshots");
    expect(md).toContain("`abc1234`");
    expect(md).toContain("### /dashboard");
    expect(md).toContain("Main dashboard");
    expect(md).toContain(
      "![/dashboard](https://screenshots.tractorbeam.ai/o/r/pr-1/dashboard.png)",
    );
    expect(md).toContain("### /settings");
    expect(md).toContain("_Generated by visual-diff_");
  });

  it("omits description line when empty", () => {
    const md = buildCommentMarkdown("abc1234", [
      { route: "/", description: "", url: "https://example.com/img.png" },
    ]);

    expect(md).not.toMatch(/\n\n\n/);
    expect(md).toContain("![/](https://example.com/img.png)");
  });
});
