import { describe, it, expect } from "vitest";
import {
  screenshotR2Key,
  logsR2Key,
  messagesR2Key,
  buildPublicUrl,
  buildCommentMarkdown,
} from "../src/worker/storage";

describe("screenshotR2Key", () => {
  it.each([
    ["/dashboard", "owner/repo/sandbox-1/dashboard.png", "simple route"],
    [
      "/settings/profile",
      "owner/repo/sandbox-1/settings-profile.png",
      "nested route",
    ],
    ["/", "owner/repo/sandbox-1/index.png", "root route"],
    [
      "/foo?bar=baz",
      "owner/repo/sandbox-1/foobarbaz.png",
      "special characters",
    ],
  ])("slugifies %s -> %s (%s)", (route, expected) => {
    expect(screenshotR2Key("owner", "repo", "sandbox-1", route)).toBe(expected);
  });
});

describe("logsR2Key", () => {
  it("builds correct R2 key for logs", () => {
    expect(logsR2Key("acme", "widget", "abc123")).toBe(
      "acme/widget/abc123/agent.log",
    );
  });

  it("handles special characters in owner/repo names", () => {
    expect(logsR2Key("my-org", "my.repo", "run-1")).toBe(
      "my-org/my.repo/run-1/agent.log",
    );
  });
});

describe("messagesR2Key", () => {
  it("builds correct R2 key for messages", () => {
    expect(messagesR2Key("acme", "widget", "abc123")).toBe(
      "acme/widget/abc123/messages.json",
    );
  });
});

describe("buildPublicUrl", () => {
  it("builds correct public URL from R2 key", () => {
    expect(buildPublicUrl("acme/widget/run-1/dashboard.png")).toBe(
      "https://screenshots.tractorbeam.ai/acme/widget/run-1/dashboard.png",
    );
  });

  it("handles keys with special characters", () => {
    expect(buildPublicUrl("my-org/my.repo/run/settings-profile.png")).toBe(
      "https://screenshots.tractorbeam.ai/my-org/my.repo/run/settings-profile.png",
    );
  });
});

describe("buildCommentMarkdown", () => {
  it("builds markdown with screenshots", () => {
    const md = buildCommentMarkdown("abc1234567890", [
      {
        route: "/dashboard",
        description: "Main dashboard",
        url: "https://screenshots.tractorbeam.ai/o/r/pr-1/dashboard.png",
      },
      {
        route: "/settings",
        description: "Settings page",
        url: "https://screenshots.tractorbeam.ai/o/r/pr-1/settings.png",
      },
    ]);

    expect(md).toContain("## Visual Diff Screenshots");
    expect(md).toContain("`abc1234`");
    expect(md).toContain("### /dashboard");
    expect(md).toContain("Main dashboard");
    expect(md).toContain(
      "![/dashboard](https://screenshots.tractorbeam.ai/o/r/pr-1/dashboard.png)",
    );
    expect(md).toContain("### /settings");
    expect(md).toContain("_Generated by visual-diff_");
  });

  it("omits description line when empty", () => {
    const md = buildCommentMarkdown("abc1234", [
      { route: "/", description: "", url: "https://example.com/img.png" },
    ]);

    expect(md).not.toMatch(/\n\n\n/);
    expect(md).toContain("![/](https://example.com/img.png)");
  });
});
