import type { Env, UploadedScreenshot } from "./types";

const R2_PUBLIC_DOMAIN = "screenshots.tractorbeam.ai";

// ---------------------------------------------------------------------------
// Log persistence (R2)
// ---------------------------------------------------------------------------

/** R2 key prefix for a run: {owner}/{repo}/{sandboxId} */
function runPrefix(owner: string, repo: string, sandboxId: string): string {
  return `${owner}/${repo}/${sandboxId}`;
}

/** R2 key where a run's logs are stored. */
export function logsR2Key(
  owner: string,
  repo: string,
  sandboxId: string,
): string {
  return `${runPrefix(owner, repo, sandboxId)}/agent.log`;
}

/** R2 key where a run's agent messages are stored. */
export function messagesR2Key(
  owner: string,
  repo: string,
  sandboxId: string,
): string {
  return `${runPrefix(owner, repo, sandboxId)}/messages.json`;
}

/** Upload the current agent.log contents to R2. */
export async function syncLogsToR2(
  env: Env,
  owner: string,
  repo: string,
  sandboxId: string,
  content: string,
): Promise<void> {
  await env.LOGS.put(logsR2Key(owner, repo, sandboxId), content, {
    httpMetadata: { contentType: "text/plain" },
  });
}

/** Upload the current agent messages to R2. */
export async function syncMessagesToR2(
  env: Env,
  owner: string,
  repo: string,
  sandboxId: string,
  messages: unknown[],
): Promise<void> {
  await env.LOGS.put(
    messagesR2Key(owner, repo, sandboxId),
    JSON.stringify(messages),
    { httpMetadata: { contentType: "application/json" } },
  );
}

/** Read logs from R2. Returns null if not found. */
export async function getLogsFromR2(
  env: Env,
  owner: string,
  repo: string,
  sandboxId: string,
): Promise<string | null> {
  const obj = await env.LOGS.get(logsR2Key(owner, repo, sandboxId));
  if (!obj) return null;
  return obj.text();
}

/** Read persisted messages from R2. Returns null if not found. */
export async function getMessagesFromR2(
  env: Env,
  owner: string,
  repo: string,
  sandboxId: string,
): Promise<unknown[] | null> {
  const obj = await env.LOGS.get(messagesR2Key(owner, repo, sandboxId));
  if (!obj) return null;
  return obj.json();
}

/**
 * Build the R2 object key for a screenshot.
 * Format: {owner}/{repo}/pr-{number}/{route-slug}.png
 */
export function buildR2Key(
  owner: string,
  repo: string,
  prNumber: number,
  route: string,
): string {
  const slug =
    route
      .replace(/^\//, "")
      .replace(/\//g, "-")
      .replace(/[^a-zA-Z0-9-]/g, "") || "index";
  return `${owner}/${repo}/pr-${prNumber}/${slug}.png`;
}

/**
 * Build the public URL for a screenshot stored in R2.
 */
export function buildPublicUrl(key: string): string {
  return `https://${R2_PUBLIC_DOMAIN}/${key}`;
}

/**
 * Upload a screenshot buffer to R2 and return the public URL.
 */
export async function uploadScreenshot(
  env: Env,
  key: string,
  data: ArrayBuffer | Uint8Array,
): Promise<string> {
  await env.SCREENSHOTS.put(key, data, {
    httpMetadata: { contentType: "image/png" },
  });
  return buildPublicUrl(key);
}

/**
 * Build the PR comment markdown from uploaded screenshots.
 */
export function buildCommentMarkdown(
  commitSha: string,
  screenshots: UploadedScreenshot[],
): string {
  const lines = [
    "## Visual Diff Screenshots",
    "",
    `Screenshots taken at commit \`${commitSha.slice(0, 7)}\`.`,
    "",
  ];

  for (const s of screenshots) {
    lines.push(`### ${s.route}`, "");
    if (s.description) {
      lines.push(s.description, "");
    }
    lines.push(`![${s.route}](${s.url})`, "");
  }

  lines.push("---", "", "_Generated by visual-diff_");
  return lines.join("\n");
}
