import type { Env, UploadedScreenshot } from "./types";

const R2_PUBLIC_DOMAIN = "screenshots.tractorbeam.ai";

// ---------------------------------------------------------------------------
// Log persistence (R2)
// ---------------------------------------------------------------------------

/** R2 key where a run's logs are stored. */
export function logsR2Key(sandboxId: string): string {
  return `logs/${sandboxId}/agent.log`;
}

/** Upload the current agent.log contents to R2. */
export async function syncLogsToR2(
  env: Env,
  sandboxId: string,
  content: string,
): Promise<void> {
  await env.SCREENSHOTS.put(logsR2Key(sandboxId), content, {
    httpMetadata: { contentType: "text/plain" },
  });
}

/** Read logs from R2. Returns null if not found. */
export async function getLogsFromR2(
  env: Env,
  sandboxId: string,
): Promise<string | null> {
  const obj = await env.SCREENSHOTS.get(logsR2Key(sandboxId));
  if (!obj) return null;
  return obj.text();
}

/**
 * Build the R2 object key for a screenshot.
 * Format: {owner}/{repo}/pr-{number}/{route-slug}.png
 */
export function buildR2Key(
  owner: string,
  repo: string,
  prNumber: number,
  route: string,
): string {
  const slug = route
    .replace(/^\//, "")
    .replace(/\//g, "-")
    .replace(/[^a-zA-Z0-9-]/g, "")
    || "index";
  return `${owner}/${repo}/pr-${prNumber}/${slug}.png`;
}

/**
 * Build the public URL for a screenshot stored in R2.
 */
export function buildPublicUrl(key: string): string {
  return `https://${R2_PUBLIC_DOMAIN}/${key}`;
}

/**
 * Upload a screenshot buffer to R2 and return the public URL.
 */
export async function uploadScreenshot(
  env: Env,
  key: string,
  data: ArrayBuffer | Uint8Array,
): Promise<string> {
  await env.SCREENSHOTS.put(key, data, {
    httpMetadata: { contentType: "image/png" },
  });
  return buildPublicUrl(key);
}

/**
 * Build the PR comment markdown from uploaded screenshots.
 */
export function buildCommentMarkdown(
  commitSha: string,
  screenshots: UploadedScreenshot[],
): string {
  const lines = [
    "## Visual Diff Screenshots",
    "",
    `Screenshots taken at commit \`${commitSha.slice(0, 7)}\`.`,
    "",
  ];

  for (const s of screenshots) {
    lines.push(`### ${s.route}`, "");
    if (s.description) {
      lines.push(s.description, "");
    }
    lines.push(`![${s.route}](${s.url})`, "");
  }

  lines.push("---", "", "_Generated by visual-diff_");
  return lines.join("\n");
}
