import type { Env, UploadedScreenshot } from "./types";

const R2_PUBLIC_DOMAIN = "screenshots.tractorbeam.ai";

/**
 * Build the R2 object key for a screenshot.
 * Format: {owner}/{repo}/pr-{number}/{route-slug}.png
 */
export function buildR2Key(
  owner: string,
  repo: string,
  prNumber: number,
  route: string,
): string {
  const slug = route
    .replace(/^\//, "")
    .replace(/\//g, "-")
    .replace(/[^a-zA-Z0-9-]/g, "")
    || "index";
  return `${owner}/${repo}/pr-${prNumber}/${slug}.png`;
}

/**
 * Build the public URL for a screenshot stored in R2.
 */
export function buildPublicUrl(key: string): string {
  return `https://${R2_PUBLIC_DOMAIN}/${key}`;
}

/**
 * Upload a screenshot buffer to R2 and return the public URL.
 */
export async function uploadScreenshot(
  env: Env,
  key: string,
  data: ArrayBuffer | Uint8Array,
): Promise<string> {
  await env.SCREENSHOTS.put(key, data, {
    httpMetadata: { contentType: "image/png" },
  });
  return buildPublicUrl(key);
}

/**
 * Build the PR comment markdown from uploaded screenshots.
 */
export function buildCommentMarkdown(
  commitSha: string,
  screenshots: UploadedScreenshot[],
): string {
  const lines = [
    "## Visual Diff Screenshots",
    "",
    `Screenshots taken at commit \`${commitSha.slice(0, 7)}\`.`,
    "",
  ];

  for (const s of screenshots) {
    lines.push(`### ${s.route}`, "");
    if (s.description) {
      lines.push(s.description, "");
    }
    lines.push(`![${s.route}](${s.url})`, "");
  }

  lines.push("---", "", "_Generated by visual-diff_");
  return lines.join("\n");
}
